<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/ScriptedSmtpsServer.cs" Link="Testing/ScriptedSmtpsServer.cs" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="../../src/NovaEmail.Mail/NovaEmail.Mail.csproj" />
    <ProjectReference Include="../../src/NovaEmail.Storage/NovaEmail.Storage.csproj" />
  </ItemGroup>
</Project>
